### ISSUE TITLE
Request Author to update the links for dataset repository.

### ISSUE THREAD

**Issue by visujadhav** [Mohamedelrefaie/DrivAerNet#1]
Links for Dataset is not provided in README file. Request author to provide the links and dataset.

**Comment by afshawnlotfi** [comment]
yeah I am very confused where the dataset is since the paper was saying it was open

**Comment by Mohamedelrefaie** [comment]
Apologies for the confusion regarding the dataset access. We are currently in the process of making the DrivAerNet dataset available for public use. A subset of the dataset is already accessible [here](https://www.dropbox.com/scl/fo/mnnnogykaoixdus9j0wr7/AO0PywI7VAZ1_ZL0e2HcjaA?rlkey=iox7cd8510800iinkqalph9zx&dl=0).

**Comment by Shisongdenghuft** [comment]
> 对于数据集访问造成的混淆，我们深表歉意。我们目前正在将 DrivAerNet 数据集开放给公众使用。数据集的子集已可[在此处](https://www.dropbox.com/scl/fo/mnnnogykaoixdus9j0wr7/AO0PywI7VAZ1_ZL0e2HcjaA?rlkey=iox7cd8510800iinkqalph9zx&dl=0)访问。
Can a subset of the dataset be made public again? Because the original dataset is simply too large

**Comment by Shisongdenghuft** [comment]
> Apologies for the confusion regarding the dataset access. We are currently in the process of making the DrivAerNet dataset available for public use. A subset of the dataset is already accessible [here](https://www.dropbox.com/scl/fo/mnnnogykaoixdus9j0wr7/AO0PywI7VAZ1_ZL0e2HcjaA?rlkey=iox7cd8510800iinkqalph9zx&dl=0).

Can a subset of the dataset be made public again? Because the original dataset is simply too large
