### ISSUE TITLE
The computation of R2

### ISSUE THREAD

**Issue by gcblqqqqqqqqqqqqqqq** [Mohamedelrefaie/DrivAerNet#11]
Hello, I would like to ask you about the calculation of R². While reproducing your code, I found that R² is consistently negative, and I haven't figured out the reason yet. I want to ask you if in your code R² is calculated for each batch and then averaged, is it correct to average R²? I wonder if the negative value of my R² might be related to this. Perhaps you could give me some guidance. Thank you!

**Comment by Mohamedelrefaie** [comment]
It's hard to judge why your R² is negative without more details. Could you clarify: which model are you training (RegDGCNN, RegPointNet, or the graph model)? Are you using the parametric data or 3D meshes? If it's 3D meshes, are you working with raw STLs or preprocessed point clouds?
In general, R² is just used to evaluate the model's performance but the mse is the loss used for training.

**Comment by gcblqqqqqqqqqqqqqqq** [comment]
Hello,The model I trained is RedgCNN, and the dataset used is DrivAerNet_STLs_Combined. The R2 value has consistently been negative  and   LOSS is decreasing and the performance is decent.
