### ISSUE TITLE
files needed to run DrivAerNet_tutorial.py

### ISSUE THREAD

**Issue by cctutum** [Mohamedelrefaie/DrivAerNet#14]
There are several files needed to read the DrivAerNet_tutorial.py (such as AeroCoefficients_DrivAerNet_FilteredCorrected.csv, STL files in DrivAerNet_STLs_Combined-folder, etc.). Will these be available later?
Are the parametric models viewed in a CAD software or with PyVista?
Thanks!

**Comment by Mohamedelrefaie** [comment]
Please see:
https://www.dropbox.com/scl/fo/mnnnogykaoixdus9j0wr7/AO0PywI7VAZ1_ZL0e2HcjaA?rlkey=7uo51ka60kgdhc1fgqf0begss&st=d503c8dt&dl=0

**Comment by cctutum** [comment]
Thank you very much!
