### ISSUE TITLE
Inquiry regarding data

### ISSUE THREAD

**Issue by shijiasheng** [Mohamedelrefaie/DrivAerNet#15]
The DrivAerNet_v1 datasets are presented in page https://github.com/Mohamedelrefaie/DrivAerNet?tab=readme-ov-file

And the official address of the datasets download is on Dropbox: https://www.dropbox.com/scl/fo/mnnnogykaoixdus9j0wr7/AO0PywI7VAZ1_ZL0e2HcjaA?rlkey=iox7cd8510800iinkqalph9zx&dl=0

But when I open the address, there is error. I hope authors can fix this issues.

**Comment by Mohamedelrefaie** [comment]
Fixed! Thank you. 
Please see the new link.

**Comment by Mohamedelrefaie** [comment]
The full dataset is now released on Harvard Dataverse:
https://dataverse.harvard.edu/dataverse/DrivAerNet

**Comment by Mohamedelrefaie** [comment]
The full dataset is now released on Harvard Dataverse:
https://dataverse.harvard.edu/dataverse/DrivAerNet
