### ISSUE TITLE
some issues while trying to download the dataset

### ISSUE THREAD

**Issue by liuye6666** [Mohamedelrefaie/DrivAerNet#19]
Dear Author,

Thank you very much for sharing the dataset on Harvard Dataverse. I truly appreciate your efforts in making this valuable resource available. However, I have encountered some issues while trying to download the dataset using Globus as per the instructions, which have made it challenging to download the complete dataset.

The main issues are as follows:

Since each dataset contains nearly 8,000 files, Globus often freezes, making it impossible to download the entire dataset.
If I try to avoid selecting all files at once and instead select a smaller number of samples (e.g., 200), Globus still reports an error during transfer submission with the message "there was an error in transfer submission. biig."
Selecting a very small number of samples (e.g., 1 to 10 files) works, but repeating this process to download the entire dataset is highly time-consuming and labor-intensive.
Dear author, I sincerely appreciate your generosity in sharing the dataset, and I am eager to use it for my research. May I ask if there is a better way to download the dataset? Or do you have any recommendations for resolving these issues?

Thank you for your time and help!

Best regards,

**Comment by parsaTheMaker** [comment]
Hello Dear Author,

Thank you for the amazing dataset. I have been dealing with the same issue as the main post here. I was wondering if any mirror or additional method for accessing the dataset has been introduced ever since. This dataset will greatly improve my research in numerical calculations.

Kind regards, Parsa

**Comment by Mohamedelrefaie** [comment]
Thank you for reaching out! Please send me an email so I can connect you directly with the Harvard Dataverse team.

In the meantime, we are working on releasing a smaller version of the dataset to improve accessibility. Additionally, we are exploring the integration of DrivAerNet with Huggingface.

Looking forward to hearing from you!
