### ISSUE TITLE
Math problem need help

### ISSUE THREAD

**Issue by wangguan1995** [Mohamedelrefaie/DrivAerNet#2]
for car 0501.vtk

![image](https://github.com/Mohamedelrefaie/DrivAerNet/assets/39621324/5e557a1c-12c1-46b1-89f9-c75376158721)

Fd = Ff + Fp = Cd * 1/2 * (rho * v^2 ) * A_ref = 0.326779573 * 0.5 * (1.2 * 30 * 30) * 2.48347697559532 = 438.236754 N

![image](https://github.com/Mohamedelrefaie/DrivAerNet/assets/39621324/f3c50aec-a5af-43c1-ba97-3faded410d7b)

Here is a big gap between [272 N] and [438 N], need help for solve this problem, thanks

**Comment by wangguan1995** [comment]
btw 0132.stl projection area missing

**Comment by Mohamedelrefaie** [comment]
Hi, 
we've implemented simpleFoam, an incompressible solver for our simulations and the momentum equation uses the kinematic pressure.
![image](https://github.com/Mohamedelrefaie/DrivAerNet/assets/86707575/85bd35e6-8a4a-42b0-9a15-94d474a2505e)
So, please make sure to multiply your pressure with the density (rho=1.2kg.m^-3). 
In addition, verify that the tangential vectors are used for wall shear stress, not normals. This should give you the correct drag force/coefficient. 

One important thing is that the drag values reported in the AeroCoefficients_DrivAerNet_FilteredCorrected.csv are averaged over several iterations, which might differ from direct calculations that typically represent only the latest iteration! 
We used RegDGCNN to directly estimate Cd from a 3D mesh. This contrasts with other approaches like neural operators, which first predict pressure and wall shear stresses and then integrate these to derive Cd. 
To address this, we will release the drag history and statistical metrics such as mean drag and standard deviation to provide a more reliable benchmark across different estimation methods.

**Comment by wangguan1995** [comment]
# Paraview Files:
 https://www.dropbox.com/scl/fo/65x8hu3um1a566ba2uq6c/AJMAgTrk43ql7O1Q6jTAuzo?rlkey=33bm4viz5s49jrti61hizmagz&st=1fs6y434&dl=0
# CheckList:
- ✓ density 1.2
- ✓wss integrated over cars without normal
- x averaged pressure(cant measure that now, but I believe fluctuation would be less than 5% if converged)

# My assumption:
 - [Cd] is often calculated by 【Openfoam controlDict forceCoeffs】, I believe that u Cd is correct.
 - [cell pressure] will be better. My evidence is : A common used SIMPLE algo put [p] in cell center, and  
https://www.openfoam.com/documentation/user-guide/6-solving/6.2-numerical-schemes

# Plus
RegDGCNN to directly estimate Cd. This is more directly accurate, and end-to-end than other methods. I really wish I could contribute something to make it  better.

**Comment by Mohamedelrefaie** [comment]
Hi @wangguan1995,

Thank you for your input and the positive feedback about our work. I've reviewed your approach and I suggest the following adjustments:

**Pressure Force Calculation**: Please include fluid density in the pressure force equation: 
so it should be Fp_vtk = Integrate(p * Normals_X*rho_inf)  and not Fp_vtk = Integrate(p * Normals_X) 

**Wall Shear Stress:** The stress should be calculated using tangential forces, not surface normals.

I will update the projected areas file asap.

Regarding your question on CFD physics near the boundary layer: yes, it is well-studied. However, our study aimed to balance simulation fidelity with shape variation. Simulating fine meshes for 4,000 designs would require more than 120TB, which isn't feasible at all. Our focus was to provide a large variation in shape, essential for the conceptual design phase, allowing engineers and designers to better explore the design space.

Additionally, very high-fidelity fine simulations with low design variation may cause models to overfit to specific car design. For deep learning models to generalize well to out-of-domain designs, it’s critical that they are trained on diverse geometrical modifications.

If you'd like to contribute to this work, we welcome pull requests and will acknowledge contributions in future publications.
