### ISSUE TITLE
RegDGCNN code for surface field prediction

### ISSUE THREAD

**Issue by phanindrasp** [Mohamedelrefaie/DrivAerNet#20]
Hello,

The current DGCNN code is for scalar (drag) prediction. Is the surface field prediction code not uploaded yet or did I miss it?

**Comment by Mohamedelrefaie** [comment]
Thank you for your interest! At the moment, there are no plans to release the models for surface field prediction.

**Comment by Mohamedelrefaie** [comment]
https://github.com/Mohamedelrefaie/DrivAerNet/tree/main/RegDGCNN_SurfaceFields
