### ISSUE TITLE
how to find label

### ISSUE THREAD

**Issue by wangyunsang** [Mohamedelrefaie/DrivAerNet#22]
Where can I find detailed annotations for various car components (29 labels), such as wheels, side mirrors, and doors.thank you

**Comment by Mohamedelrefaie** [comment]
If you have ANSA you can easily access those labels. We are currently working on releasing the labels separately from ANSA. Will keep you posted.

**Comment by Mohamedelrefaie** [comment]
Dataset annotation is now available at [DrivAerNet++: Annotations](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CAWRXI).
