### ISSUE TITLE
Release DrivAerNet++ on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [Mohamedelrefaie/DrivAerNet#24]
Hello @Mohamedelrefaie 🤗

I'm Niels from the Hugging Face team. I came across your DrivAerNet++ work (https://huggingface.co/papers/2406.09624) and its impressive 8,000 car design dataset.  It looks very valuable for the automotive and machine learning communities.

Would you be open to hosting DrivAerNet++ on the Hugging Face Hub (https://huggingface.co/datasets)? This would increase its visibility and enable easy access for researchers and practitioners, who could then load it directly using the `datasets` library:

```python
from datasets import load_dataset
dataset = load_dataset("your-hf-org-or-username/DrivAerNet++")
```

We support various formats, including WebDataset (https://huggingface.co/docs/datasets/en/loading#webdataset), which works well for large image/video datasets. The Hub also provides a convenient dataset viewer (https://huggingface.co/docs/hub/en/datasets-viewer) for exploring the data directly in the browser.

We can also link the dataset to your paper page to further enhance its discoverability.  Let me know if you're interested or have any questions.  Happy to help with the process!

Cheers,

Niels

**Comment by NielsRogge** [comment]
Update, lit looks like https://huggingface.co/datasets/MoElrefaie/DrivAerNet is already on the hub, would be great to link it in the README of this Github repo so that people can find it :)

**Comment by Mohamedelrefaie** [comment]
Thank you very much, Niels! 
We truly appreciate your kind words and are excited about the opportunity to integrate DrivAerNet++ into Hugging Face. I'll send you an email shortly to discuss the details further. Looking forward to collaborating!
