### ISSUE TITLE
Alternative modeling for 3-wheeled cars

### ISSUE THREAD

**Issue by hatonthecat** [Mohamedelrefaie/DrivAerNet#25]
Hi, really interesting paper and software approach.

I am wondering if using the training model on different car shapes, like an Aptera or Elio, which have an aerodynamic-focused design with extremely low drag coefficient, can be used in a new study. They appear to have been based on optimized aerodynamic simulations in the mid-00s. It might not mix/train well with 4-wheel designs, but I have a repository where I catalogue open-source designs.

**Comment by Mohamedelrefaie** [comment]
Thank you for your interest! 
Yes, the knowledge gained from DrivAerNet++ can indeed be transferred to different downstream tasks, especially when analyzing aerodynamic-focused designs. The dataset's size and diversity make it particularly valuable for studying such cases, as it provides a robust foundation for understanding car body characteristics and aerodynamic behavior. Leveraging this for your study could yield insightful results!
