### ISSUE TITLE
details of the CFD simulation

### ISSUE THREAD

**Issue by Shisongdenghuft** [Mohamedelrefaie/DrivAerNet#3]
Hi, I'm a beginner in surrogate modeling of vehicle drag coefficients and would really appreciate the open source of this dataset. I now want to use OpenFoam to calculate the drag coefficient myself, but I cannot ensure that my simulation results are correct. Can you provide more detailed simulation details?

Thank you! Your research and data sets are very helpful to us.

**Comment by Mohamedelrefaie** [comment]
Thank you for your interest in our dataset and for reaching out. We are pleased to hear that our data has been useful to you. We plan to release a detailed validation study for our CFD simulations soon. Unfortunately, we will not be releasing the meshing/CFD code. However, you can find the STLs used for the CFD simulations and defining boundary conditions in the "DrivAerNet_STLs_DoE" folder. Additionally, you can compare your drag and flow field results with reference data from the literature, as the DrivAer model has been extensively benchmarked. We hope this helps!
