### ISSUE TITLE
Math Problem V2.0

### ISSUE THREAD

**Issue by wangguan1995** [Mohamedelrefaie/DrivAerNet#4]
# previously on 
https://github.com/Mohamedelrefaie/DrivAerNet/issues/2#issue-2267563258
After the bugfix for the first version of Drag force caculation

# Paraview Files:
- download
 https://www.dropbox.com/scl/fo/65x8hu3um1a566ba2uq6c/AJMAgTrk43ql7O1Q6jTAuzo?rlkey=33bm4viz5s49jrti61hizmagz&st=1fs6y434&dl=0

- how to load
![image](https://github.com/Mohamedelrefaie/DrivAerNet/assets/39621324/39088ac9-d4bf-477c-9ece-1b68489fe3e3)

# CheckList:
- ✓ density 1.2
- ✓ WSS integrated over cars without normal
- x averaged pressure(can't measure that now, but I believe fluctuation would be less than 5% if converged)

# My assumption:
 - [Cd] is often calculated by 【Openfoam controlDict forceCoeffs】, I believe Cd is correct.

# Plus：
- Another problem I have noticed is that the [wall shear stress] direction is not aligned with velocity, this confused me. Regarding my CFD simulations with some commercial software like Fluent, is CFD physics near the boundary well-studied?
<img width="1032" alt="image" src="https://github.com/Mohamedelrefaie/DrivAerNet/assets/39621324/520e46f9-eb9f-42e0-bbe9-f330a1e67ab6">

- RegDGCNN to directly estimate Cd. This is more directly accurate, and end-to-end than other methods. I wish I could contribute something to make it better.

_Originally posted by @wangguan1995 in https://github.com/Mohamedelrefaie/DrivAerNet/issues/2#issuecomment-2081829640_

**Comment by Mohamedelrefaie** [comment]
please see https://github.com/Mohamedelrefaie/DrivAerNet/issues/2#issuecomment-2088505046
