### ISSUE TITLE
The output

### ISSUE THREAD

**Issue by LearnedVector** [Mohamedelrefaie/DrivAerNet#5]
Hello, I just want to better understand this code base. 

The model only predicts a single scale value for drag coefficient? Do you have a version that also predicts the velocity and pressure field?

**Comment by cseander** [comment]
I'm trying to train a GCN model to predict the pressure in each point, so far the results are not very satisfactory but I'm doing some progress and I will try more sophisticated methods for creating the graph eventually.

**Comment by Mohamedelrefaie** [comment]
Hey,

Yeah, you're right. The current RegDGCNN model is focused on predicting a single scalar value for the drag coefficient from a 3D STL mesh in an end-to-end manner. 
We're working on a modified version that can handle surface fields predictions like wall shear stresses and pressure, and we'll be publishing it soon. Keep an eye out for that!

Cheers!
