### ISSUE TITLE
STL File Units

### ISSUE THREAD

**Issue by JonathanQTran** [Mohamedelrefaie/DrivAerNet#6]
Hello,

I am attempting to use this dataset to compare with vehicle geometries from my own simulations. However when I load in the stl file the scale seems to be different than my geometries (which are saved with mm). Geometries from the DrivAerNet dataset are much smaller when loaded.

What units are the stl files for this dataset generated in?

Thanks.

**Comment by Mohamedelrefaie** [comment]
Hey Jonathan,

Our dataset is based on the 1:1 scaled DrivAer model, with the smallest length being 4344 mm and the largest length being 5210 mm.
![image](https://github.com/Mohamedelrefaie/DrivAerNet/assets/86707575/b2eeaa2c-0ab7-49b7-b4df-72aecaaff3b3)

Thanks.
