### ISSUE TITLE
Average Drag and Downforce/Lift coefficient data (plus others)

### ISSUE THREAD

**Issue by apcode** [Mohamedelrefaie/DrivAerNet#7]
I see the data download has the csv file of Average Drag per design.  Do you plan to also release the average downforce and centre of pressure for each design?

Also, is there a plan to release the same data that was released for v1?  the surface pressure vtk and other files.
And perhaps the full simulation data,

Awesome paper and dataset.

**Comment by Mohamedelrefaie** [comment]
Hi Alan,

Thank you for your positive feedback on our paper and dataset!

Yes, we're planning on releasing the average downforce (Cl) along with Cl,r (rear) and Cl,f (front) and Cm (moment coefficient). Additionally, we will also release the surface pressure VTK and other files (including other data modalities such as part annotations, surface, and volumetric CFD fields) after the review process is completed and the paper is peer-reviewed in the next couple of weeks.

**Comment by uanu2002** [comment]
It's a good dataset, but i can only find csv files containing "drag". Where can I find files containing "lift" or "moment"?
